<?php
/**
 *                                _                                   _
 *       /'\_/`\                 ( )             /'\_/`\             ( )_
 *       |     | _   _  _ __    _| |   __   _ __ |     | _   _   ___ | ,_)   __   _ __  _   _
 * (`\/')| (_) |( ) ( )( '__) /'_` | /'__`\( '__)| (_) |( ) ( )/',__)| |   /'__`\( '__)( ) ( )
 *  >  < | | | || (_) || |   ( (_| |(  ___/| |   | | | || (_) |\__, \| |_ (  ___/| |   | (_) |
 * (_/\_)(_) (_)`\___/'(_)   `\__,_)`\____)(_)   (_) (_)`\__, |(____/`\__)`\____)(_)   `\__, |
 *                                                      ( )_| |                        ( )_| |
 *                                                      `\___/'                        `\___/'
 *
 * Copyright (C) 2016-2026 NetherGames Network
 *
 * This is private software, you cannot redistribute and/or modify it in any way
 * unless given explicit permission to do so. If you have not been given explicit
 * permission to view or modify this software you should take the appropriate actions
 * to remove this software from your device immediately.
 *
 * @author matcracker
 *
 */
declare(strict_types=1);

namespace murdermystery\gamemodes\infection;

use murdermystery\gamemodes\infection\tasks\MatchTimeInfectionTask;
use murdermystery\gamemodes\MMArena;
use murdermystery\MurderMystery;
use murdermystery\utils\Items;
use murdermystery\utils\MMChance;
use NetherGames\NGEssentials\utils\CustomIcon;
use pocketmine\entity\Skin;
use pocketmine\player\Player;
use pocketmine\utils\TextFormat;
use function array_diff;
use function base64_decode;
use function count;
use function in_array;

class MMArenaInfection extends MMArena
{
    /** @var Player[] */
    private array $infected = [];
    /** @var int */
    private int $alphaDeaths = 0;

    /** @var array */
    private array $kills = [];
    /** @var array */
    private array $skinData = [];

    public function __construct(MurderMystery $plugin, int $modeId, int $id, bool $privateGame)
    {
        parent::__construct($plugin, $modeId, $id, $privateGame);

        $this->listener = new InfectionArenaListener($this);
    }

    public function addInfected(Player $player): void
    {
        $this->infected[] = $player;
    }

    public function addKill(Player $player): void
    {
        $this->kills[$player->getName()]++;

        $this->getScoreboard()->setLine([$player], 5, CustomIcon::KILLS . TextFormat::GREEN . $this->getKills($player));
    }

    public function getKills(Player $player): int
    {
        return $this->kills[$player->getName()];
    }

    public function addAlphaDeath(): void
    {
        $this->alphaDeaths++;
    }

    public function getAlphaDeaths(): int
    {
        return $this->alphaDeaths;
    }

    public function canRespawn(): bool
    {
        return !($this->alphaDeaths >= 2 || $this->getAlpha() === null);
    }

    public function getAlpha(): ?Player
    {
        return $this->infected[0] ?? null;
    }

    public function queuePlayer(Player $player): void
    {
        $this->kills[$player->getName()] = 0;
        $this->skinData[$player->getName()] = $player->getSkin();

        parent::queuePlayer($player);
    }

    public function startGame(): void
    {
        $array = [];

        $array[14] = '';
        $array[13] = CustomIcon::GAMEMODE . ':' . TextFormat::GREEN . 'Survivor';
        $array[12] = '';
        $array[11] = CustomIcon::HOURGLASS . TextFormat::GREEN . '5:00';
        $array[10] = '';
        $array[9] = CustomIcon::STEVE_HEAD . TextFormat::GREEN . count($this->getPlayers());
        $array[8] = CustomIcon::ZOMBIE_HEAD . TextFormat::RED . 0;
        $array[7] = '';
        $array[6] = CustomIcon::ALEX_HEAD . TextFormat::GREEN . 'Alive';
        $array[5] = CustomIcon::KILLS . TextFormat::GREEN . 0;
        $array[4] = '';
        $array[3] = CustomIcon::MAP . TextFormat::GREEN . $this->getMapDisplayName();
        $array[2] = '';
        $array[1] = CustomIcon::NETHERGAMES . TextFormat::GOLD . 'ngmc.co';

        $this->getScoreboard()->setLines($this->getPlayers(), $array);

        foreach ($this->getPlayers() as $player) {
            if (!$this->isSpectator($player)) {
                $player->setNameTag(''); //TODO: Remove when MCPE fix that
            }

            if ($this->isInfected($player) && $this->getGameSettings()->hasAlwaysCompass()) {
                $player->getInventory()->setItem(Items::COMPASS, Items::getInnocentLocator());
            }

            $player->teleport($this->getPlugin()->getArenaConfig()->getRandomSpawn($this));
        }

        parent::startGame();

        $this->getPlugin()->getScheduler()->scheduleRepeatingTask(new MatchTimeInfectionTask($this), 20);
    }

    /**
     * @return Player[]
     */
    public function getSurvivors(): array
    {
        return array_diff($this->getPlayers(false), $this->getInfected(), $this->getSpectators());
    }

    /**
     * @return Player[]
     */
    public function getInfected(): array
    {
        return $this->infected;
    }

    public function resetPlayer(Player $player): void
    {
        parent::resetPlayer($player);

        if ($this->isSpectator($player) && $player->getSkin() === $this->getInfectedSkin()) {
            $player->setSkin($this->getOriginalSkin($player));
            $player->sendSkin();
        }
    }

    public function isAlpha(Player $player): bool
    {
        return $this->getAlpha() === $player;
    }

    public function isInfected(Player $player): bool
    {
        return in_array($player, $this->infected, true);
    }

    public function getOriginalSkin(Player $player): Skin
    {
        return $this->skinData[$player->getName()];
    }

    public function assignChance(Player $player): void
    {
        if ($this->isInfected($player)) {
            $this->getPlugin()->getChanceHandler()->setPlayerChance($player, MMChance::INFECTED, 1);
        } else {
            $this->getPlugin()->getChanceHandler()->addPlayerChange($player, MMChance::INFECTED, mt_rand(1, 2));
        }
    }

    public function addParticipation(Player $player, array $data, bool $guildXP = false): void
    {
        if ($this->isWinner($player)) {
            if ($this->isAlpha($player)) {
                $data[self::DATA_CREDITS][] = [
                    'Win as Alpha',
                    5
                ];
            } elseif ($this->isInfected($player)) {
                $data[self::DATA_CREDITS][] = [
                    'Win as Infected',
                    4
                ];
            } else {
                $data[self::DATA_CREDITS][] = [
                    'Win as Innocent',
                    12
                ];
            }
        }

        parent::addParticipation($player, $data, $guildXP);
    }

    public function getStreaksKey(): ?string
    {
        if ($this->isPrivateGame()) return null;
        return strtolower($this->getPlugin()->getMinigameTag() . "_" . $this->getPlugin()->getModes()[$this->getModeId()]);
    }

    public function removeInfected(Player $player): void
    {
        $this->infected = array_diff($this->infected, [$player]);
    }

    final public function getWaitingPopup(Player $player): string
    {
        return '§cInfected chance:§6 ' . $this->getPlugin()->getChanceHandler()->getChancePercentage($this, $player, MMChance::INFECTED) . '%%';
    }

    public function getInfectedSkin(): Skin
    {
        return new Skin('Standard_Custom', base64_decode('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHMyX/KRwT/21POv8uIBb/Tjgp/2lMOP89Kx//OCYb/0c1Jv9MOir/Uy4r/0glJP9MJyX/SCgm/0o4J/9FNSb/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaEs5/2VHNP9MNSf/MSIZ/zcxLP9GPTX/ZUc0/2JGM/9INib/QDAj/0Y1Jf9JJyT/RzYm/0gmJf9FNSb/SDYm/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADkmGv89Kh3/STYq/zUrJf9CNiz/W0Y3/0w0Jv9GLyL/TToq/0QyJP8BAQD/AAAA/wAAAP8AAAD/QjEj/0o3J/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABnSDb/blA8/2NOQP8/NC7/PjQu/zQpI/8yJBv/Pisf/1E+LP9GNSX/AwMC/wAAAP8AAAD/BAQE/0c2Jf9RPy3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOygb/zgrIP85Lyn/QTYw/2ZRRP9fSjz/cVM+/2lLN/9OOir/RTUl/wAAAP8AAAD/AAAA/wAAAP9GNif/Tjwq/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4tIP8+Kx7/7dCp/yYgHP85Lyn/MCUf/zAiGP8tIBX/Sjgn/0MyJP8CAQH/AAAA/wAAAP8AAAD/RzYn/0o5J/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4bN6/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABeQS//37F3//K/gP+vhnX/UDos/1A5Kv9lRzT/Zkk2/0Y0JP9AMCL/RDIl/0Y1Jf9HNyf/RDMk/0IyJP9JOCf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADTomb/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARjEk/9+zef+rgG//36xu/zAhGP8/Kx//SjUm/15CMf9FNSX/ZVtD/0w5Kf9OOyn/Tjsp/0w5KP9OPCz/RzUn/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA27+a/9qoav8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1JRr/RzIk/z0rHv9OOCn/QzEj/1A6Kv9nSjf/STQm/zgoHP/JqYH/qoBw/9qmaP9ALSD/MSQZ/zknG/82JRv/RTEk/0o1J/9ALSH/TDUn/z0qHf9NNij/RzEk/zsqHv84KB3/TTcp/z0qHv84KBz/QS8i/1A5Kv8qHRT/RTEj/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzrSR/9m9mf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOScc/0s1KP89Kh7/Vj4w/0EvIv+pf27/4K91/92vdP+OZ1f/z62F/6l/b//aqWv/MyUc/0EuIf+adlj/bE80/z4sIP9JMyX/Py0f/1I8Lv9GNCf/QS4h/7STef+sjHH/MyQa/2VHNP8zJBn/RTMl/zwsIf9NNif/KhwT/zknG/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADqv4v/5r6N/+S9jf/dwJv/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAroB2/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC8iGP9BLyH/RD84/1xHOv/0y5X/4bN8/6p/bv/mt3r/16lx/++7fv/Or4j/nnZm/7uYe/88MCX/uJN2/6hzSP89LCD/SzQl/zsuJP9hTD//PTAn/0g2Kv85Jhn/so9y/zUmG/9ONyj/QDEl/11IOv9FOC//clVC/yweFP81JRv/AAAAAAAAAAAAAAAAAAAAAAAAAADatIH/w5mF/9m7lf/nvIP/8cSJ//bLk/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKV2av8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1Lij/TEM8/0VAOv9ZSDz/6cyn/+bFnf/Xto//m3Jh/5xzYv/evJP/3a10/8uhbv+JYFb/fWBG/6R/YP+/i2H/Py0f/0c1J/9AMyr/WEY7/0o9NP9YT0n/SUA5/zQuKP8nIh7/RTw1/0Y3Lf9fVlD/TklD/31hTf86NS//RT43/wAAAAAAAAAAAAAAAAAAAAAAAAAA9cuW/wAAAAAAAAAAAAAAANq8lv8AAAAAAAAAAO/Utf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJyMe/zk0Lv85NTD/SUM//6Z5bP/yxo3/8sCC/9usc//Prob/l2tc/8+yjf/OpW7/xJpm/2IjJP9JEBD/3LmQ/ysfFf85LSL/Ny0m/6+Ncf9NSEP/V05I/zcxLP8pJSD/JyEd/zo1L/9YUEr/S0ZB/0NAO/9TSkP/wp+E/0Q8Nf8AAAAAAAAAAAAAAAAAAAAAuYuB/wAAAAAAAAAA5cii//HJlP8AAAAAAAAAAOrDkv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAu42D/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyQhf8AAAAAAAAAACciHv8mIRz/NDAr/zw3NP87NjL/tYR5/6B0ZP/FpX3/yZhc/7WUav+KYFH/19XN/+Hg2f/YuJL/fxob/6WIcP98Z1b/IRYP/7uZff9GQDv/QDw2/0M9N/8sJyL/JiEc/0U1J/8mIh3/MzAq/0lDP/8+OTX/wqCE/8SghP8wKiX/AAAAAAAAAAAAAAAAAAAAAAAAAACzgnb/8MSI/+nAi//MoYz/262X/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtYJ3/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACqfXL/qHls/wAAAAAnIx7/UUAx/1dHNf8wKyf/U0Av/8ydYv/Fl17/g1tK/1AxKP9lQzz/dkA8/y8MDP8qGxv/d2VR/5B5Zf+AaVX/d2hU/1VLPP+hkm3/Lyol/3RdRv8qJCD/koJg/5CBXv9YRDD/QDEj/zgtIP8uKib/U0Q3/7eSdP9cSTT/Tj4v/wAAAAAAAAAAAAAAAAAAAAAAAAAA+M6Z/8ifi/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcllA/3leQ/9+YkX/WUo5/8Sid/++nHL/w5NY/6R4Q/9MMSn/cT48/3E9Ov/e3db/9/Xu/2IwLv9tWkn/YUkz/2BSQv+Jelr/iXta/3RUOP9yWkP/blU//6aAWv++kWH/Z040/3FXPP9OOyv/VEEv/1VBMP9/XUD/iXlZ/2pROP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHpFQP9wOjf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUGhz/GB0e/xQaHf8TGBv/EAwM/xwSEv8cExL/EQ4M/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFyMR/xomFP9dRzP/Y0s4/15FMv+beFv/kW5S/5FwU/8RFAz/ERUN/xEVDf8OEQn/EBQM/xAUDP8PFAz/DxIL/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZVhR/2JQR/9IOzX/OCwo/y8lIf9DIiX/Sz04/zYsJ/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGR8g/xkeIf8aICH/GR8g/x0TE/8PDAv/EA0L/x8UFP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgjEf9oUTv/XUo6/2VSQv9mVET/Xks7/6mBYf+ScFT/EBQM/xAVDP8VGxH/FBkQ/xQZD/8RFg3/DhIJ/w0RCv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGxaVP9gUEf/VUU+/00/Of8QCQr/EQkK/xEICf8RDQ3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQaHP8XHB//GB4g/xgdIP8QDQz/HxUT/xgUEv8cEhL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZJRL/Z086/2NRQP9kUkL/ZlRE/19MO/+pg2T/mXVX/w0QCf8PFAv/EhUM/xYbEf8QEwv/ExkP/xAUDP8OEgr/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABrWlP/XElC/1BBOv89Mi3/EAgJ/xENDf9JJCj/OjEr/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWGx3/Fxwe/xgeIP8WGh3/GxER/xIPDf8fFRT/EQ4N/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFyMS/xklEv9eSDL/dlc7/3ZXPP+Xc1b/mXVX/4hoTf8PEgv/DhEK/xAUDP8SFw7/DxML/xAUDP8RFA3/DhEK/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZVdR/11KQv86Lyr/Migj/zMpJv8VEg//Niwo/ywVF/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdIiX/GBwg/xwhJP8aHiL/GBsf/xwhI/8aHyX/MDk+/xUaHf8ZHSD/FRoc/xccHv8JERH/DBMT/w0UFP8TFxn/ExgN/w8UCv8SFg3/ExcO/xIPDf8TEA7/U0Eu/4hoTv+Ed1n/hmZM/3tdRf92WkP/eVxF/3pdRv97X0f/UjAv/3hbRP+CZEv/hmZM/4ZnTv8QFAv/ExcP/xsWFP8hGxf/V0pF/1RHQv9WS0T/VEhD/1VKRP9IOzT/Myki/yYfGv8TGA7/GBwS/x0lFf8WGxH/JyEc/zMpI/9EODL/XlJM/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGR4i/ycxNP8wOz//GyAk/yAmKv83REn/ICYr/xsgJP8YHiD/HyUp/ycvNP8eJCb/ERkZ/xIUFv8WHB//GB4f/xEVC/8UGRD/ERYL/xIXDf8QDQv/MSgi/w0MCv+FZUv/gHFU/4t9Xv+HZ03/g2VL/39iSf9zWEL/dFlD/1UzMf9/YEf/gmNL/4N1V/8bJBP/GyMT/xkVEv8nIBv/GxYU/0xBPP9WTEb/R0A8/01CPP9KQDr/cWJZ/xcUE/8UEQ//FRsP/xkeEv8aIRP/FxwQ/xMQDf8TEA3/Qzw5/05DPf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACozN/8nMTX/NEFF/yUrMP8iKC3/JSww/z5KUf8eJCr/JSwv/yk0OP8rNjr/GR4h/xQYGv8aICP/JSww/xIXGv8UGQ7/FRkP/xQeD/8WGxD/EhAO/0s+OP9HOTD/EA0M/6B6XP+bdlj/f3RZ/4xsUf98X0f/gGJK/1UyMv96XEX/d2tP/5KEZv8dJBP/KTkf/yojBv88Mgv/GhUS/w0RCv8rKCb/MS0s/zc0Mv8rJyX/KSUk/0M8Ov8eKBb/JzEe/xwkFP8eJxX/ISgX/xccD/8YHRP/GB0T/zYzMP8tKCf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxPED/SFNa/0JNVf8rNjr/PUZP/0ROV/9CTFX/JCsx/ykxNf83P0T/N0BF/yMrL/8eIyb/LTQ4/zhARP8dJCf/EBQM/xAaC/8bKBP/FBkO/xkTEf9EOjT/bl5X/zoyLf+shmn/j3Fa/66Jav+Na1L/h2ZN/4BiSf+DZU3/iWlP/w8TC/8xOSj/OEcu/ywmI/9FOTL/RD0g/yEmHf8PFAv/NTws/0NROf95Yk3/Mjoq/zI6Kv9NZEH/SVY8/yMnHv8VGw7/HiQW/x8lGP8aIBP/LjMn/zU9Lf9BTzf/Mjor/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO0ZI/1FbY/9PWmL/OUNH/4FnS/9KVFz/T1pi/zM6Pv81PUD/QkxQ/0FKT/8zOj7/KS8y/zhAQ/8wNjj/KjAy/xQfDv8aJhH/ICwW/xMYDf8OFQr/DgwK/zAtK/9JQj7/rItx/6iIbf9qPz7/XTU0/4xsUf+CZEr/ICwW/x0lFf8SFw7/IisZ/zw3Nf9XTUf/OzUz/zA0K/8iKxn/EBUM/zQ8K/94YUz/dmBL/zY+Lf+xooL/Q0s7/zxCNP8tMyf/blY//3FZRP90XEX/blY//ycsI/85PTL/P0c3/zM7K/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBKTf9YYmj/TVld/2pUQ/9PXGL/ZXF8/01ZXf88RUr/QUtP/0xUWf9HT1L/PUVK/y00Nv8yNzn/NDc6/zhARP8UHw7/HywX/x8sF/8VGQ7/Mj8l/y1AIf8pJiT/Rj87/35tZP87My7/qYJi/1dHQP8mIBz/HRgW/yIuGP8aIhL/HhgW/yQeG/9QRiD/aVwt/0tFKf8pLCP/FRoQ/xMYDv9jTTr/tKaI/4RnT/9MMC7/qohs/6CTc/+1knb/mnpi/4BjSf9/V1L/h2tR/39hR/9RQDL/aVRC/4ltVf9kTjv/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2PEH/R1FU/0xZXf81OUD/NjxC/09YXv9IUFX/Nz1C/y40Nv9FT1L/Q0tN/zM5PP8wNTf/QEhL/zk/Qf87Q0f/CwgH/xIPDv8UEg//DQsK/x4YFf8ZFxT/Lisb/y0rKf8vLSv/My0r/2ZVTf83LSb/KCId/yIbF/8aFRP/HCQV/x8bF/80LCb/NjAa/z45Jf8/Oib/Ni8s/yEbGf8gGxj/rIll/6eXdv/broH/gmhO/7Omhf/myKL/9dSr/6yVeP+ohWL/m2Rf/9msfv+CZEr/clpG/7Wnif+3jWz/jG1R/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANTtA/zk/RP8/SUz/MTU7/y80Of8/SU3/SVNY/zlBR/8mLC//MDU3/zlARP8qMTP/NT1B/zA1OP8sMTT/KzIz/xoVEv8jHRj/IhsX/xsWFP81LCb/UkM5/2NVTP9USkT/alxT/01CPf8zKST/HBcV/x8bGP8bFRP/FRIQ/xAMC/8qIh//OC0m/0tBO/9DPTj/V01I/0g+OP88MSr/LCUf/6SAWv/ZrHz/mV9a/6R/Wv+ulHf/vaSE/6CSdf+rknX/ckVB/9yufv/er3//o39a/4loS/+Pb1T/n5Bw/4hnS/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQYHP8aHiP/LDM4/yYsMv8jKjD/Ki81/x8iJv8eIyb/GB0g/xwhJP8gJin/HyQo/xYaHf8cICT/HSIl/xUaHf8ODAr/EQ0N/xQRD/8MCQf/GBIQ/yEbF/8yKyb/NC8r/z41Mf8hHx3/IBoX/yYeHP8SEA3/EQ4N/w8MCv8WEhD/HBcT/x0WFP8vKSb/NTAt/zYyLv8rJiL/IBsX/x0YFf92Wj3/oHxW/6J9V/95XED/gG5V/66Vdf+pkHD/e19H/3VWOv+lgFr/pYBa/3hXPP9fRjD/iGVJ/4hmSv9gRjH/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlJib/NzY3/zY2Nv8lJSX/Pz8//1lZWf9YWFj/UlJS/ygoKP86Ojr/Nzc3/yMiI/8lJST/ODk4/zc2N/8jIiP/DhIK/xIYDf8SFw3/EBQL/xQYEP8OEQn/FRkR/y9AJf89Si7/NUIo/zVDJ/8cKhP/ERcL/xgfEv8WHRD/GyMU/x8tFv8wPST/MT4k/yk5Hv8aHhX/FBcO/w4RCf8SFg7/JyEc/yggHP8wKCP/HBcU/xoUEf8aFRP/PDEq/xcUEf8XEhH/FAoL/xMICv8VERD/FAoM/xIICf8cFRP/Ix0X/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFRYW/x0dHv8fHh7/GBkY/zMzM/8uLy//W1ta/y8uL/8TExP/ICAg/x0cHf8VFRX/FA0N/yEhIf8eHh7/FxEQ/wsOCP8NEAn/DREK/w8SC/8hEwr/DQAA/xEBAP8QFgv/EBYM/xklE/8SBAP/AwIB/w0RCv8NEQr/EBML/w0RCf8MEAj/ERUN/xMXDv8SFwz/KBcL/xMXDv8OEwr/HxII/xQSDv83LSf/MBQV/xcTEv8RDQz/HBYT/0I1Lv8cGBT/GAkK/xcICv8nIRz/HBcU/xMKC/8OBgf/MhYW/w8MCv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABUODf8SCQr/FQ4O/xUODf8XEA//CgYG/wkEBP8IBAT/FQ8N/xMMDP8UDQz/FA0N/xUODv8YERD/FxEQ/xILC/8OEwv/DREK/w0RCv8LDgj/DBAJ/wwQCP8QEwz/EhYN/wcJBf8jLBr/HSQU/w4SCv8MEAn/DQ8J/w4RCv8OEgv/HhEI/xsOBf8fEQf/IxUJ/yITCP8QFAv/DhML/wkMBv8yKSP/LRIT/ysQEv8hDw//MCch/z4yLf9aSUH/FxIP/xoODv8jHBj/Ix0Z/xoVEv8SDw3/Kw8Q/zEXGP8TEA7/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATGBv/FBod/xgdHv8UGhz/EQ4M/xwTEv8cEhL/EAwM/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOCwo/0g7Nf9iUEf/ZVhR/zYsJ/9LPTj/QyIl/y8lIf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGR8g/xogIf8ZHiH/GR8g/x8UFP8QDQv/DwwL/x0TE/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE0/Of9VRT7/YFBH/2xaVP8RDQ3/EQgJ/xEJCv8QCQr/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgdIP8YHiD/Fxwf/xQaHP8cEhL/GBQS/x8VE/8QDQz/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9Mi3/UEE6/1xJQv9rWlP/OjEr/0kkKP8RDQ3/EAgJ/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWGh3/GB4g/xccHv8WGx3/EQ4N/x8VFP8SDw3/GxER/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMigj/zovKv9dSkL/ZVdR/ywVF/82LCj/FRIP/zMpJv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXHB7/FRoc/xkdIP8VGh3/MDk+/xofJf8cISP/GBsf/xoeIv8cIST/GBwg/x0iJf8TFxn/DRQU/wwTE/8JERH/FhsR/x0lFf8YHBL/ExgO/yYfGv8zKSL/SDs0/1VKRP9USEP/VktE/1RHQv9XSkX/XlJM/0Q4Mv8zKSP/JyEc/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHiQm/ycvNP8fJSn/GB4g/xsgJP8gJiv/N0RJ/yAmKv8bICT/MDs//ycxNP8ZHiL/GB4f/xYcH/8SFBb/ERkZ/xccEP8aIRP/GR4S/xUbD/8UEQ//FxQT/3FiWf9KQDr/TUI8/0dAPP9WTEb/TEE8/05DPf9DPDn/ExAN/xMQDf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkeIf8rNjr/KTQ4/yUsL/8eJCr/PkpR/yUsMP8iKC3/JSsw/zRBRf8nMTX/KjM3/xIXGv8lLDD/GiAj/xQYGv8XHA//ISgX/x4nFf8cJBT/JzEe/x4oFv9DPDr/KSUk/ysnJf83NDL/MS0s/ysoJv8tKCf/NjMw/xgdE/8YHRP/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjKy//N0BF/zc/RP8pMTX/JCsx/0JMVf9ETlf/PUZP/ys2Ov9CTVX/SFNa/zE8QP8dJCf/OEBE/y00OP8eIyb/GiAT/x8lGP8eJBb/FRsO/yMnHv9JVjz/TWRB/zI6Kv8yOir/eWJN/0NROf81PCz/Mjor/0FPN/81PS3/LjMn/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzo+/0FKT/9CTFD/NT1A/zM6Pv9PWmL/SlRc/4FnS/85Q0f/T1pi/1FbY/87Rkj/KjAy/zA2OP84QEP/KS8y/25WP/90XEX/cVlE/25WP/8tMyf/PEI0/0NLO/+xooL/Nj4t/3ZgS/94YUz/NDwr/zM7K/8/Rzf/OT0y/ycsI/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD1FSv9HT1L/TFRZ/0FLT/88RUr/TVld/2VxfP9PXGL/alRD/01ZXf9YYmj/QEpN/zhARP80Nzr/Mjc5/y00Nv9/YUf/h2tR/39XUv+AY0n/mnpi/7WSdv+gk3P/qohs/0wwLv+EZ0//tKaI/2NNOv9kTjv/iW1V/2lUQv9RQDL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzOTz/Q0tN/0VPUv8uNDb/Nz1C/0hQVf9PWF7/NjxC/zU5QP9MWV3/R1FU/zY8Qf87Q0f/OT9B/0BIS/8wNTf/gmRK/9msfv+bZF//qIVi/6yVeP/11Kv/5sii/7Omhf+CaE7/266B/6eXdv+siWX/jG1R/7eNbP+1p4n/clpG/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKjEz/zlARP8wNTf/Jiwv/zlBR/9JU1j/P0lN/y80Of8xNTv/P0lM/zk/RP81O0D/KzIz/ywxNP8wNTj/NT1B/6N/Wv/er3//3K5+/3JFQf+rknX/oJJ1/72khP+ulHf/pH9a/5lfWv/ZrHz/pIBa/4hnS/+fkHD/j29U/4loS/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8kKP8gJin/HCEk/xgdIP8eIyb/HyIm/yovNf8jKjD/Jiwy/ywzOP8aHiP/FBgc/xUaHf8dIiX/HCAk/xYaHf94Vzz/pYBa/6WAWv91Vjr/e19H/6mQcP+ulXX/gG5V/3lcQP+ifVf/oHxW/3ZaPf9gRjH/iGZK/4hlSf9fRjD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjIiP/Nzc3/zo6Ov8oKCj/UlJS/1hYWP9ZWVn/Pz8//yUlJf82Njb/NzY3/yUmJv8jIiP/NzY3/zg5OP8lJST/FREQ/xMICv8UCgv/FxIR/xcUEf88MSr/GhUT/xoUEf8cFxT/MCgj/yggHP8nIRz/Ix0X/xwVE/8SCAn/FAoM/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFRUV/x0cHf8gICD/ExMT/y8uL/9bW1r/Li8v/zMzM/8YGRj/Hx4e/x0dHv8VFhb/FxEQ/x4eHv8hISH/FA0N/xwXFP8nIRz/FwgK/xgJCv8cGBT/QjUu/xwWE/8RDQz/FxMS/zAUFf83LSf/FBIO/w8MCv8yFhb/DgYH/xMKC/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQNDf8UDQz/EwwM/xUPDf8IBAT/CQQE/woGBv8XEA//FQ4N/xUODv8SCQr/FQ4N/xILC/8XERD/GBEQ/xUODv8aFRL/Ix0Z/yMcGP8aDg7/FxIP/1pJQf8+Mi3/MCch/yEPD/8rEBL/LRIT/zIpI/8TEA7/MRcY/ysPEP8SDw3/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=='), '', 'geometry.humanoid.custom');
    }
}