<?php
declare(strict_types=1);

namespace lobby\entity\custom;

use lobby\Lobby;
use lobby\utils\BaseTrait;
use lobby\utils\PlayerUtils;
use NetherGames\NGEssentials\player\Translator;
use pocketmine\entity\Entity;
use pocketmine\entity\EntitySizeInfo;
use pocketmine\entity\Location;
use pocketmine\event\entity\EntityDamageEvent;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\player\Player;
use pocketmine\world\ChunkLoader;
use pocketmine\world\format\Chunk;

class IconMarker extends Entity implements ChunkLoader
{
    use BaseTrait;

    private array $targetPlayers = [];

    public function __construct(Location $location, private string $tokenIdentifier = "", private bool $collectable = false, ?CompoundTag $nbt = null)
    {
        parent::__construct($location, $nbt);
        $chunkX = $location->getFloorX() >> Chunk::COORD_BIT_SIZE;
        $chunkZ = $location->getFloorZ() >> Chunk::COORD_BIT_SIZE;
        $location->getWorld()->registerChunkLoader(
            loader: $this,
            chunkX: $chunkX,
            chunkZ: $chunkZ,
            autoLoad: true
        );

        if ($this->collectable) {
            $this->setNameTagAlwaysVisible(true);
        }
        $this->setHasGravity(false);
    }

    public static function getNetworkTypeId(): string
    {
        return "ng:lobby_icon_marker";
    }

    public function attack(EntityDamageEvent $source): void
    {
        parent::attack($source);
        $source->cancel();
    }

    public function spawnTo(Player $player): void
    {
        if (in_array($player->getXuid(), $this->targetPlayers, true)) {
            if ($this->collectable) {
                PlayerUtils::playSound($player, "random.levelup", 1);
                $player->sendTitle(Translator::getTranslationPlayer($player, "secret.unlocked.title", Translator::TYPE_SUCCESS));
            }

            parent::spawnTo($player);
        }
    }

    public function addTo(Player $player): void
    {
        $this->targetPlayers[] = $player->getXuid();
    }

    public function removeFrom(Player $player): void
    {
        unset($this->targetPlayers[array_search($player->getXuid(), $this->targetPlayers, true)]);
    }

    public function saveNBT(): CompoundTag
    {
        $nbt = parent::saveNBT(); // TODO: Change the autogenerated stub
        $nbt->setString("tokenIdentifier", $this->tokenIdentifier);
        $nbt->setByte("collectable", $this->collectable ? 1 : 0);

        return $nbt;
    }

    public function getName(): string
    {
        return "IconMarker";
    }

    public function onCollideWithPlayer(Player $player): void
    {
        if (!$this->collectable) return;
        if (!in_array($player->getXuid(), $this->targetPlayers)) return;
        $this->flagForDespawn();
        Lobby::getInstance()->getFeaturesManager()->getTokens()->playPickupAnimation($player, $this->tokenIdentifier);
    }

    protected function getInitialSizeInfo(): EntitySizeInfo
    {
        return new EntitySizeInfo(0.5625, 0.375);
    }

    protected function getInitialDragMultiplier(): float
    {
        return 0;
    }

    protected function getInitialGravity(): float
    {
        return 0;
    }
}